[build]
  command = "npm install && npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

[build.environment]
  NODE_OPTIONS = "--max_old_space_size=4096"

[dev]
  command = "npm start"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
